### Requests done with REST-Client for VSCode (humao.rest-client) ###
@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

###

// #############
// Users requests
// #############

GET http://{{host}}/users

###

GET http://{{host}}/users/1

###

POST http://{{host}}/users
Content-Type: {{contentType}}

{
    "username": "test"
}

###

PATCH http://{{host}}/users/1
Content-Type: {{contentType}}

{
    "username": "Updated",
    "socketID": ""
}

###

DELETE http://{{host}}/users/1

###

// ##############
// Stats requests
// ##############

GET http://{{host}}/stats

###

GET http://{{host}}/stats/1

###

PATCH http://{{host}}/stats/1
Content-Type: {{contentType}}

{
    "played": 1,
    "win": 2,
    "lose": 1,
    "ratio": "1.5"
}

###

// #################
// Messages requests
// #################

POST http://{{host}}/messages
Content-Type: {{contentType}}

{
    "author": 1,
    "channel": {"id": 1},
    "data": "Bouh!"
}

###

DELETE http://{{host}}/messages/1

###

// #################
// Channels requests
// #################

POST http://{{host}}/channels
Content-Type: {{contentType}}

{
    "name": "Channel1",
    "owner": {"id": 1},
    "admins": [{"id": 1}, {"id": 2}],
    "members": [{"id": 1}, {"id": 3}, {"id": 4}],
    "mutes": [{"id": 4}]
}

###

DELETE http://{{host}}/channels/6

###

// ################
// Matches requests
// ################

POST http://{{host}}/matches
Content-Type: {{contentType}}

{
    "players": [{"id": 1}, {"id": 2}],
    "score": [7, 10]
}

###

PATCH http://{{host}}/matches/2
Content-Type: {{contentType}}

{
    "players": [{"id": 4}, {"id": 5}],
    "score": [42, 21],
    "winner": {"id": 4}
}

###

DELETE http://{{host}}/matches/1