### Requests done with REST-Client for VSCode (humao.rest-client) ###
@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json
@userLogin = lchapren

###

// Get all users
GET http://{{host}}/users

###

// Get specific user
# @userLogin = 11
GET http://{{host}}/users/{{userLogin}}

###

// Post a new user
POST http://{{host}}/users
Content-Type: {{contentType}}

{
    "username": "josayko"
}

###

PATCH http://{{host}}/users/1
Content-Type: {{contentType}}

{
    "username": "Updated"
}

###

// Delete a specific user
# @userLogin = 6
DELETE http://{{host}}/users/4

###

POST http://{{host}}/messages
Content-Type: {{contentType}}

{
    "author": 1,
    "channel": {"id": 10},
    "data": "This is just a test message, to see if everything is working"
}

###

POST http://{{host}}/channels
Content-Type: {{contentType}}

{
    "name": "Channel21",
    "owner": {"id": 1},
    "admins": [{"id": 1}, {"id": 2}],
    "members": [{"id": 1}, {"id": 3}, {"id": 4}],
    "mutes": [{"id": 4}],
    "bans": [{"id": 5}]

}

###

DELETE http://{{host}}/channels/1

###

POST http://{{host}}/matches
Content-Type: {{contentType}}

{
    "players": [{"id": 1}, {"id": 2}],
    "score": [7, 10],
    "winner": {"id": 4}
}

###

PATCH http://{{host}}/matches/1
Content-Type: {{contentType}}

{
    "players": [{"id": 1}, {"id": 2}]
}

###

DELETE http://{{host}}/matches/4
